### ISSUE TITLE
No mediaset video streaming from outside Italy

### ISSUE THREAD

**Issue by rewe68** [phate89/Mediaset-Play-plugin.video.videomediaset#17]
Hi phate89,

I tried different ways to run mediaset-videos from outside Italy.
My preferred way is to use it with Kodi 18.0 and your plugin without VPN, but with smartdnsproxy 
Unfortunately this produces following Kodi-errors:

19:23:06.697 T:5236  NOTICE: plugin.video.videomediaset: Starting module 'Video Mediaset' version '1.3.2' with command '?mode=playMediaset&id=864471'
19:23:07.198 T:4556  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.videomediaset/?mode=playMediaset&id=864471
19:23:07.198 T:4556   ERROR: CCurlFile::Stat - Failed: Unsupported protocol(1) for plugin://plugin.video.videomediaset/?mode=playMediaset&id=864471
19:23:07.201 T:6360  NOTICE: Creating InputStream
19:23:09.198 T:6360   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
19:23:09.198 T:6360   ERROR: CCurlFile::Open failed with code 403 for http://vod06.msf.ticdn.it/farmunica/2018/07/236431_164acc74fc3a2f/164acc74fc3a2f-20_0.mp4:
19:23:09.308 T:6360   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
19:23:09.308 T:6360   ERROR: CCurlFile::Open failed with code 403 for http://vod06.msf.ticdn.it/farmunica/2018/07/236431_164acc74fc3a2f/164acc74fc3a2f-20_0.mp4:
19:23:09.309 T:6360   ERROR: XFILE::CFileCache::Open - failed to open source <http://vod06.msf.ticdn.it/farmunica/2018/07/236431_164acc74fc3a2f/164acc74fc3a2f-20_0.mp4>
19:23:09.309 T:6360   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.videomediaset/?mode=playMediaset&id=864471]
19:23:09.309 T:6360  NOTICE: CVideoPlayer::OnExit()

If I use VPN (trial) it works with Kodi and Firefox.
If I use only SmartDNSProxy with Firefox and Mediaset-Userlogin, I can see all videos
Webiste-Messages:
"Registrati a Mediaset Play: è gratuito e avrai accesso illimitato a tutti i video, alle dirette, alla tua lista personale e ai tuoi contenuti preferiti."
and
"Per vedere questo contenuto è necessario registrarsi."

This is the link on the mediaset website with Login:
https://www-o.mediaset.net/video/ilsegreto/mercoledi-18-luglio_F308755501000602
or
https://www.mediasetplay.mediaset.it/video/ilsegreto/mercoledi-18-luglio_F308755501000602

For the same video with Kodi I got following Link:
http://vod06.msf.ticdn.it/farmunica/2018/07/236431_164acc74fc3a2f/164acc74fc3a2f-20_0.mp4

The first two links work with Firefox and SmartDNSProxy. The third link doesn't work with Kodi nor with Firefox (without VPN).

Maybe there is a way to implement the Mediaset-Login and/or different video-path within your Plugin, so videos can be played without a need  to use VPN.

BTW: Live-stream with smartdnsproxy and Kodi is working.

Hope you can help me and maybe other users outside Italy.

Thanky you.
rewe68

**Comment by phate89** [comment]
Mediaset is blocking streams from abroad. Try a vpn with the new version (2.0)
