### ISSUE TITLE
Version 1.3.2 On demand Channels Doesn't work

### ISSUE THREAD

**Issue by karpediemnow** [phate89/Mediaset-Play-plugin.video.videomediaset#18]
Hi, 
with version 1.3.2 the "On demand" like "Quarto Grado" channels doesn't work.
this is the log:
https://paste.kodi.tv/iyaxeribis.kodi

Thanks!

**Comment by lpuglia** [comment]
I get the same error, does downgrading works?

**Comment by lpuglia** [comment]
older versions do not work anymore, Kodi 17.6 was freshly installed from retropie repositories. Does it work on other platform?

**Comment by phate89** [comment]
Aggiornato l'addon alla versione 2.0 con il nuovo sito
