### ISSUE TITLE
Live url changed again?

### ISSUE THREAD

**Issue by sgerwk** [phate89/Mediaset-Play-plugin.video.videomediaset#19]
Looks like the url for the live stream has been changed again.

The browser downloads 
``https://link.theplatform.eu/s/PR1GhC/3Yd92Y7_bm2Xformat=smil&auto=true&tracking=true&balance=true&assetTypes=HD,browser:SD,browser``
with referer ``https://www.mediasetplay.mediaset.it/diretta/rete4_cR4``,
and obtain the url for the mpd manifest from there.

**Comment by sgerwk** [comment]
Looks like a new plugin does it:

[github.com/kodi-bino/plugin.video.mediasetplay](github.com/kodi-bino/plugin.video.mediasetplay)

**Comment by phate89** [comment]
Aggiornato l'addon alla versione 2.0 con il nuovo sito
