### ISSUE TITLE
Merge with KodiBino

### ISSUE THREAD

**Issue by Gythion** [phate89/Mediaset-Play-plugin.video.videomediaset#20]
Why don't you merge your skill with the other add-on about Mediaset by KodiBino?

**Comment by phate89** [comment]
I didn't even know it existed... I checked it out and even if he started at least partially from my code (old one) it's really different...
I just just posted mine updated to official Kodi repo.. there's something major that his version have?

**Comment by Gythion** [comment]
No, you have the option: "Visti/Non visti", that the other hasn't
