### ISSUE TITLE
"Riprendi da..." non funziona

### ISSUE THREAD

**Issue by Gythion** [phate89/Mediaset-Play-plugin.video.videomediaset#21]
https://is.gd/ttg2yn

**Comment by phate89** [comment]
Purtroppo io passo il link a Kodi con l'addon inputstream che gestisce la riproduzione . Non posso fare nulla per gestire la ripresa del video.. sto guardando a un metodo per disabilitarla del tutto...

**Comment by Gythion** [comment]
Adesso hanno risolto
