### ISSUE TITLE
Il plugin non carica più i contenuti

### ISSUE THREAD

**Issue by pink102** [phate89/Mediaset-Play-plugin.video.videomediaset#28]
Il plugin non carica più i contenuti

**Comment by PatK-CodeLou** [comment]
![image](https://user-images.githubusercontent.com/67236728/103103548-bf111480-45ef-11eb-88cf-f0e593702982.png)
I'm able to view videos if I have a shortcut directly to the episode listing. There is a problem with the step where it pulls up the list of shows

**Comment by pink102** [comment]
Io visualizzo solo le dirette. Le varie cartelle sono vuote.

**Comment by Fabrizio-93** [comment]
@phate89 le cartelle all'interno di mediasetplay sono vuote puoi fixare? grazie

**Comment by mario79rm** [comment]
Io vedo sia dirette che guida tv repliche i contenuti confermo sono vuoti

**Comment by pink102** [comment]
Esatto per guida tv e dirette, ma le cartelle sono ancora vuote. Non ho le giuste competenze per fixare, ma mi metto volentieri a disposizione per qualsiasi tipo di contributo che potrei dare.

**Comment by riccardosimo** [comment]
![image](https://user-images.githubusercontent.com/8348630/103176860-91d59800-4875-11eb-9954-2b45baee3308.png)

**Comment by Gythion** [comment]
Su "Kod-on-Demand" funziona.

**Comment by typhoon51280** [comment]
Ho fissato gli endpoint e aperto la pull request #30 
Versione beta del plugin scaricabile da [plugin.video.videomediaset.v2.0.1.beta3](https://github.com/typhoon51280/plugin.video.videomediaset/releases/download/2.0.1b3/plugin.video.videomediaset.v2.0.1.beta3.zip)

**Comment by Fabrizio-93** [comment]
@typhoon51280 ottimo lavoro funziona bene, una cosa ma la cartella Programmi Tv con tutti i programmi potresti aggiungerla? manca solo quella all'appello grazie sempre

**Comment by typhoon51280** [comment]
il sito non mette + a disposizione la sezione con tutti i programmi in ordine alfabetico, per poter reintrodurre tale sezione bisognerebbe identificare se esiste una nuova api di catalogo con ordine alfabetico.
La precedente api di catalogo è tuttora presente ma non restituisce + alcun risultato

**Comment by Fabrizio-93** [comment]
@typhoon51280 il plugin non funziona più si vedono solo le dirette, puoi risolvere?

**Comment by typhoon51280** [comment]
A me sta continuando a funzionare, sicuro di usare la versione da me modificata (2.0.1-beta3) ?

![image](https://user-images.githubusercontent.com/1788522/104512662-d770bf80-55ee-11eb-8c56-dd5b33bb6e81.png)
![image](https://user-images.githubusercontent.com/1788522/104512816-1141c600-55ef-11eb-8947-ecd961b2ea47.png)
![image](https://user-images.githubusercontent.com/1788522/104512912-33d3df00-55ef-11eb-8042-68c17bec91d9.png)

**Comment by pink102** [comment]
Un grande ringraziamento a typhoon51280 per il suo impegno. Confermo che la tua beta funziona. Mancano ancora i link ai programmi tv.
Non so come, ma mi metto a disposizione per aiutare. Grazie di nuovo.

**Comment by Fabrizio-93** [comment]
confermo che funziona l'ho disinstallato è ora le cartelle sono piene, spero che amplierai l'addon con le categorie mancati, in ogni caso grazie per il tuo lavoro

**Comment by AnonymousMhl** [comment]
> 
> 
> @typhoon51280 confermo che funziona ora le cartelle sono piene, spero che amplierai l'addon con le categorie mancati, in ogni caso grazie per il tuo lavoro

io ho scaricato la beta3 e vedo ancora le cartelle vuote cosa sbaglio?

**Comment by Mc-79** [comment]
Ciao, qualcuno è così gentile da spiegarmi come installare su Kodi questa versione beta? Ho provato a installare la versione ufficiale dal playstore e poi scaricare il file. Zip e installarlo, ma non va.

**Comment by Mc-79** [comment]
> Ho fissato gli endpoint e aperto la pull request #30
> Versione beta del plugin scaricabile da [plugin.video.videomediaset.v2.0.1.beta3](https://github.com/typhoon51280/plugin.video.videomediaset/releases/download/2.0.1b3/plugin.video.videomediaset.v2.0.1.beta3.zip)

Ciao, per favore potresti dirmi la procedura per installare la versione beta che hai fatto su Kodi. Sul mio smartphone Android non riesco a farlo, se dopo aver installato Kodi vado su "instal from zip file" e seleziono il tuo file .zip, in alto a destra mi viene una scritta "the depency on script.module.phate99 version 1.2.1-beta2 could not be satisfied."
Grazie 
![Screenshot_2021-01-17-19-13-04-649_org xbmc kodi~01](https://user-images.githubusercontent.com/77585634/104934330-4a40b880-59aa-11eb-8a70-a04b1eb10d78.jpg)
![Screenshot_2021-01-17-19-12-57-948_org xbmc kodi](https://user-images.githubusercontent.com/77585634/104934332-4b71e580-59aa-11eb-92bf-9c8b49dd8887.jpg)

**Comment by Mc-79** [comment]
> > @typhoon51280 confermo che funziona ora le cartelle sono piene, spero che amplierai l'addon con le categorie mancati, in ogni caso grazie per il tuo lavoro
> 
> io ho scaricato la beta3 e vedo ancora le cartelle vuote cosa sbaglio?

Reimposta Kodi cancellando cache e tutti i dati, riavvia Kodi e NON scaricare l'addon Mediaset play ma installa prima lo script che devi scaricare da qui: https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset/releases tramite il tasto "instal from zip file" e dopo scarichi il plugin di typhoon51280 versione beta.03 e lo installi come per il precedente.
Adesso dovrebbe funzionare!

**Comment by thinkingmik** [comment]
> Ho fissato gli endpoint e aperto la pull request #30
> Versione beta del plugin scaricabile da [plugin.video.videomediaset.v2.0.1.beta3](https://github.com/typhoon51280/plugin.video.videomediaset/releases/download/2.0.1b3/plugin.video.videomediaset.v2.0.1.beta3.zip)

Ottimo lavoro @typhoon51280! la beta 3 funziona alla grande

**Comment by MaryLu78** [comment]
Grazie mille ragazzi per la grandiosa fix!

Una domanda: vorrei partecipare (tempo permettendo) allo sviluppo di questo add-on, sono abbastanza esperto di python ed ho gia' utilizzato GitLab, ma come fate voi a debuggare il codice quando gira dentro Kodi?
C'e' un modo diretto per intgeragire e sviluppare con Kodi oppure come sempre debuggate scrivendo dentro la event log?

**Comment by phate89** [comment]
Non c'è un modo per fare il debug. Puoi loggare il codice al massimo per capire cosa non va
