### ISSUE TITLE
Canale 5 non funziona

### ISSUE THREAD

**Issue by pietrogdamico** [phate89/Mediaset-Play-plugin.video.videomediaset#29]
L'unico canale che da me non funziona è Canale 5, tutti gli altri funzionano correttamente, nonostante ci voglia un po' prima che carichino. Non è la mia connessione, ho la fibra (1GBps) di fastweb

**Comment by phate89** [comment]
A me funziona regolarmente. Se ti ricapita anche con l'ultima versione posta il log e apri un nuovo issue
