### ISSUE TITLE
ONDEMAND VUOTO

### ISSUE THREAD

**Issue by AnonymousMhl** [phate89/Mediaset-Play-plugin.video.videomediaset#31]
Purtroppo l'ondemand non funziona più, tutte le cartelle sono vuote e non è possibile più rivedere in streamiing i programmi televisivi.

**Comment by fefoweb** [comment]
C'è una PR aperta per risolvere il problema degli url da @typhoon51280... intanto puoi scaricarti una versione beta che è funzionante
[fix](https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset/issues/28)

**Comment by zizzulone** [comment]
purtroppo anche la beta non funziona piu'

**Comment by RB77** [comment]
> 
> 
> @fefoweb purtroppo anche la beta non funziona piu'

Cosa intendi? Io ho provato adesso e funziona.

Se ti riferisci alla mancanza dell'elenco dei programmi in ordine alfabetico è un problema noto ma l'add-on funziona comunque: basta cercare il programma utilizzando lo strumento "Cerca" e poi aggiungerlo ai preferiti.

**Comment by fefoweb** [comment]
> > @fefoweb purtroppo anche la beta non funziona piu'
> 
> Cosa intendi? Io ho provato adesso e funziona.
> 
> Se ti riferisci alla mancanza dell'elenco dei programmi in ordine alfabetico è un problema noto ma l'add-on funziona comunque: basta cercare il programma utilizzando lo strumento "Cerca" e poi aggiungerlo ai preferiti.

quoto e confermo....

**Comment by zizzulone** [comment]
Scusa ha installato la beta3 e funziona ! Grazie

Il giorno sab 23 gen 2021 alle 11:09 RB77 <notifications@github.com> ha
scritto:
