### ISSUE TITLE
Si può rimettere la voce "PROGRAMMI" nell'elenco principale?

### ISSUE THREAD

**Issue by manuelwizard** [phate89/Mediaset-Play-plugin.video.videomediaset#32]
Si può rimettere la voce "PROGRAMMI" nell'elenco principale? Questo eviterebbe di dover ogni volta cercare il programma desiderato con tasto cerca. THANKS

**Comment by phate89** [comment]
Non c'è più un elenco comprensivo di tutti i programmi sul sito mediaset. Bisogna per forza passare da categoria o cercarlo
