### ISSUE TITLE
Kodi matrix plugin disabilitato

### ISSUE THREAD

**Issue by Brax84** [phate89/Mediaset-Play-plugin.video.videomediaset#33]
Con kodi matrix si é disabilitato il plugin

**Comment by phate89** [comment]
Matrix richiede che venga reinviato l'addon con versione diversa. Lo sto pubblicando sulla repo ufficiale cosi poi sarà disponibile per tutti

**Comment by SiNaPsEr0x** [comment]
Ma la repository non ha nulla dentro solo L addon trailer
