### ISSUE TITLE
Latest release not working "failed due to an invalid structure"

### ISSUE THREAD

**Issue by truresma** [phate89/Mediaset-Play-plugin.video.videomediaset#34]
Hello,

i tried to install your latest release, but i always get the following error message: "failed due to an invalid structure"

I tried it on PC and Android TV with the latest Kodi v19.0 "Matrix" full wipe/fresh release with both files (-matrix and without it) but it doesn't work on either of them.

**Comment by domoticz-italia** [comment]
Hi there. Same problem here with Kodi 19 on Amazon firetv. Wait for fix. Thanks

**Comment by phate89** [comment]
did you use the official repo or the zips in release? The addon is now in the kodi official repo and works there for me..

**Comment by truresma** [comment]
> 
> 
> did you use the official repo or the zips in release? The addon is now in the kodi official repo and works there for me..

Yesterday it was not there. I will try it now, thanks.

**Comment by truresma** [comment]
Now i can install it, but it does not really work. "Guida TV" infinite loading.

**Comment by Brax84** [comment]
With zips in release "failed due to an invalid structure" why?
On Nvidia Shield in Kodi can't find Mediaset in video>add-on 
How to install? thanks

**Comment by domoticz-italia** [comment]
> did you use the official repo or the zips in release? The addon is now in the kodi official repo and works there for me..

Used only zip in release now i installed from official repo and now works great. Thanks phate89

**Comment by minoccio** [comment]
I tried zip file, with same error of invalid structure, and repository, with error of pyton 2.0

**Comment by phate89** [comment]
I need a log. do you use matrix or leia and earlier? there are 2 different zips, one specific for matrix

**Comment by minoccio** [comment]
I use leia (corelec 9.2.6). In the repository there isn't 2.0.2 Leia version , but only 2.0.0 or 2.0.2 + matrix. In the log doesn't remain nothing related of mediaset play installing

**Comment by phate89** [comment]
The addon in lega is there since yesterday (they approved it after the matrix one: https://mirrors.kodi.tv/addons/leia/plugin.video.videomediaset/). If you don't find it try forcing check for updates manually.
I'll check the zip. Did you update script.module.phatr89 and used the version without -matrix.1 init?

**Comment by minoccio** [comment]
Ok! After a refresh of repository, 2.02 was there, and install procedure works. Thank you!

**Comment by nik2143** [comment]
I have the same problem, I'm using kodi 19 on android

**Comment by SiNaPsEr0x** [comment]
![image](https://user-images.githubusercontent.com/5438823/109384186-5e51d100-78eb-11eb-9334-77d03beadd67.jpeg)

This is Only video plugin ... where is mediasetplay?
