### ISSUE TITLE
errore iniziale installazione

### ISSUE THREAD

**Issue by SiNaPsEr0x** [phate89/Mediaset-Play-plugin.video.videomediaset#35]
da problema proprio all'inizio dell'installazione... senza lasciare traccia sul log però.... proprio errore iniziale

**Comment by Gythion** [comment]
Ho risolto così. Non devi fare altro che scaricarti prima lo script e poi il plugin da queste pagine, e poi te li installi da zip.

**Comment by SiNaPsEr0x** [comment]
Il problema è questo

![BEFBC3BB-889E-4D53-A6EF-E58348892AD9](https://user-images.githubusercontent.com/5438823/109942510-8e76e680-7cd4-11eb-8931-89cce5b47b70.jpeg)

**Comment by SiNaPsEr0x** [comment]
Ho fixato installandolo da qui


https://mirrors.mit.edu/kodi/addons/matrix/plugin.video.videomediaset/

**Comment by phate89** [comment]
Da zip hai provato a usare quello con Matrix nel nome? C'è comunque un problema con la lingua italiana che crea problemi a vari addon: https://mirrors.mit.edu/kodi/addons/matrix/plugin.video.videomediaset/
L'addon è comunque disponibile sulla repo ufficiale che è esattamente dove l'hai trovato tu

**Comment by dfdario** [comment]
Quello presente su: https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset/releases non viene installato e da struttura non valida.

**Comment by SiNaPsEr0x** [comment]
Segui la mia procedura @dfdario che ha funzionato al 100%

**Comment by SiNaPsEr0x** [comment]
> Da zip hai provato a usare quello con Matrix nel nome? C'è comunque un problema con la lingua italiana che crea problemi a vari addon: https://mirrors.mit.edu/kodi/addons/matrix/plugin.video.videomediaset/
> L'addon è comunque disponibile sulla repo ufficiale che è esattamente dove l'hai trovato tu

Non appare phate89 nella tua repository.... solo comingsoon trailer c’è .... verifica che qualcosa non va nella tua repository

**Comment by phate89** [comment]
Non é nella mia repo ma in quella ufficiale di Kodi. Il link che hai preso tu é quello della repo ufficiale

**Comment by SiNaPsEr0x** [comment]
Si ma è un zip per gli update un casino .... volevo metterlo da repository

**Comment by phate89** [comment]
Non hai capito.. nella repo di Kodi lo trovi già:
https://kodi.tv/addon/plugins-video-add-ons/mediaset-play
Non c'e bisogno neanche della mia repo
