### ISSUE TITLE
mancato aggiornamento puntate daytime amici

### ISSUE THREAD

**Issue by red5454** [phate89/Mediaset-Play-plugin.video.videomediaset#36]
Innannzi tutto grazie tantissime per l'ottimo lavoro.Purtroppo ti devo segnalare che il daytime di amici20 da circa due settimane non si aggiorna piu'.
Spero ci sia rimedio!
Grazie ancora.
Max

**Comment by thinkingmik** [comment]
Ciao @red5454, potrebbe essere lo stesso problema che ho io su una serie TV. In pratica vedo solo i primi 100 elementi. 

Se fosse così prova a scaricare l'addon che ho modificato in attesa che @phate89 valuti la problematica.

https://github.com/thinkingmik/Mediaset-Play-plugin.video.videomediaset/releases/download/2.0.2-beta1/plugin.video.videomediaset.v2.0.2-beta1+matrix.1.zip

**Comment by red5454** [comment]
grande thinkingmik!!
problem solved.
Attendiamo versione ufficiale corretta, ma complimenti a tutti!

**Comment by phate89** [comment]
Sto caricando la versione fixata sulla repo ufficiale. Il problema dovrebbe esser sistemato
