### ISSUE TITLE
Limite 100 episodi

### ISSUE THREAD

**Issue by thinkingmik** [phate89/Mediaset-Play-plugin.video.videomediaset#37]
Le liste episodi, clip, ecc... delle serie TV sono limitate a 100 elementi.

Per esempio serie TV "Daydreamer", l'elenco episodi mostra solo 100 episodi

**Comment by thinkingmik** [comment]
Debuggando il sito di Mediaset Play mi sono accorto che le liste vengono recuperate con chiamate autoscroll 100 elementi alla volta. 

Per esempio: `https://feed.entertainment.tv.theplatform.eu/f/PR1GhC/mediaset-prod-all-programs?byCustomValue={brandId}{100003207},{subBrandId}{100004289}&sort=mediasetprogram$publishInfo_lastPublished|desc&range=101-200`

Da notare il parametro `range=101-200` aggiunto in automatico mentre si scrolla la lista se ci sono più di 100 elementi.

Facendo una prova aggiungendo un valore statico `args['range'] = '0-500'` a tutte le chiamate del file `resources/lib/mediaset.py` vengono recuperati tutti gli elementi. Si potrebbe anche usare la variabile del plugin "Elementi per pagina", per esempio: `args['range'] = '0-' + kodiutils.getSetting('itemsperpage')`

**Comment by energywave** [comment]
+1 alla segnalazione, mia moglie mi sta facendo due scroti così... Ottimo @thinkingmik hai debuggato già il problema! La soluzione giusta mi sembra la seconda ovvero quella di usare il parametro "Elementi per pagina" che effettivamente non capivo perchè non avesse effetto.
Mi spiace non conoscere Python altrimenti una prova l'avrei fatta direttamente... :(

**Comment by absynth-ita** [comment]
Questo stesso problema si ripercuote anche sulle clip dei servizi del programma "Le Iene" dove vengono mostrati 100 record casuali invece che gli ultimi usciti purtroppo

**Comment by energywave** [comment]
Non avevo più aggiornato. Ho provato la correzione di @thinkingmik e funziona alla perfezione. Mia moglie si guarda le sue puntate e il marito è sereno :D Tengo monitorato il repo che quando ci sarà la release dell'add-on ufficiale ritorno ad esso per non perdere gli aggiornamenti. Intanto grazie!!

**Comment by phate89** [comment]
Ho aggiunto le correzioni di thinkingmik e ho aggiunto la corretta paginazione. verrà aggiunta a breve alla repo ufficiale
