### ISSUE TITLE
Mediaset Play error - Check the log for more information

### ISSUE THREAD

**Issue by aniron79** [phate89/Mediaset-Play-plugin.video.videomediaset#42]
Ciao, innanzi tutto ringrazio phate89 per l'ottimo lavoro! Volevo segnalare che la versione plugin.video.videomediaset.v2.0.2 mi dà l'errore Mediaset Play error - Check the log for more information quando apro le dirette. Ho provato ad aggiornare manualmente alla versione plugin.video.videomediaset.v2.0.3 ma mi dà l'errore installazione fallita (Failed to Install Add-on due to an invalid structure).

Ho effettuato il test su Kodi Leia 18.8 e fino alla versione plugin.video.videomediaset.v2.0.1.beta3 l'add-on funzionava regolarmente.

Puoi aiutarmi?
Grazie

**Comment by aniron79** [comment]
Ho risolto disintallando Kodi Leia 18.8 ed installando Kodi 19 "Matrix" (l'ultima versione del plugin è già nella Repository):
plugin.video.videomediaset.v2.0.3+matrix.1

**Comment by AnonymousMhl** [comment]
io ho un problema proprio nell'installazione della repo mi dice : "the dependency on xbmc.python could not be satisfied"
