### ISSUE TITLE
Tg5 issue#37

### ISSUE THREAD

**Issue by Gythion** [phate89/Mediaset-Play-plugin.video.videomediaset#43]
Mi ricollego all'issue chiusa #37, il TG5 non ha clip aggiornate 😢, manco Striscia...

**Comment by phate89** [comment]
E' un problema completamente diverso. C'era un workaround che per striscia non fa comparire l'elenco delle stagioni ed entra diretto in quella archivio. Per quello vedi solo cose vecchie. Ma è sempre stato cosi mi sa. Purtroppo ora non ho idee su come far entrare direttamente nella stagione giusta ma ci penserò poi.
ho fatto un fix. Prova questa:
[plugin.video.videomediaset.2.0.4b1.zip](https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset/files/6212002/plugin.video.videomediaset.2.0.4b1.zip)

**Comment by Gythion** [comment]
Mi dà errore in fase d'install manuale: https://is.gd/dnOP7i

**Comment by phate89** [comment]
Scusa pensavo avessi ancora pre matrix. liho messi entrambi

**Comment by Gythion** [comment]
Continua a darmi errore in fase di update: https://is.gd/2RaNUD

**Comment by phate89** [comment]
A me l'ha installato senza problemi..puoi provare a mettere la lingua inglese prima di installarlo?

**Comment by truresma** [comment]
Ho lo stesso problema, Windows 10 64 bit + Kodi Matrix 64 bit appena installato/reinstallato in inglese

e anche su Android TV - Nvidia TV Shield Pro 64 bit non funziona

Provato entrambi i file

Molto non funziona più nell'addon ad esempio Guida TV, Dirette

**Comment by AnonymousMhl** [comment]
raga io non capisco perchè sulla mia Leia 18.9 non riesco ad installare la distro 2.0.3 + matrix e nemmeno quella senza matrix, ho visto che a molti da questo errore, cosa sbaglio?

**Comment by phate89** [comment]
Ok  ho rilasciato la versione con i vari fix:
https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset/releases/tag/2.0.4
dovrebbe arrivare a breve anche su mia repo o su quella ufficiale
