### ISSUE TITLE
2.0.4 non si installa

### ISSUE THREAD

**Issue by AnonymousMhl** [phate89/Mediaset-Play-plugin.video.videomediaset#45]
Salve amici, non riesco a montare il plugin 2.0.4 mi dice quando provo ad installarlo da zip che la struttura non è valida.

**Comment by pink102** [comment]
Anche io ho provato ad installare il nuovo plugin e mi da errore di struttura invalida, sia su firestick che su tv box, sia con kodi 18.9 che con kodi 19. Cosa posso fare?

**Comment by pink102** [comment]
Anche la versione 2.03 mi da gli stessi problemi. Sia normale che matrix

**Comment by pink102** [comment]
Ho la soluzione. All'interno del file zip manca la cartella del plugin. Basta aggiungerla

**Comment by AnonymousMhl** [comment]
aspetta non ho capito, io ho scaricato la distro 2.0.4 ed ho installata la distro 18.9 leila.

**Comment by phate89** [comment]
Nella versione finale ho sistemato il problema:
https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset/releases/tag/2.0.4
