### ISSUE TITLE
Repo phate89 non si installa 

### ISSUE THREAD

**Issue by AnonymousMhl** [phate89/Mediaset-Play-plugin.video.videomediaset#46]
Salve amici, sto provando ad installare la repo di phate89 su kodi 18.9, premetto che utilizzo un raspberry in cui utilizzo libreelec che monta la disto kodi citata precedentamente. Il messaggio di errore è il seguente: the dependency on xbmc.python could not be satisfied” .

**Comment by phate89** [comment]
La repo segue lo sviluppo ufficiale. Serve quinsi al momento kodi 19 o superiore. Stavo cercando un modo di rendere compatibili con entrambe le versioni ma al momento non ho avuto tempo

**Comment by AnonymousMhl** [comment]
ok, ti ringrazio per aver risposto, cercavo di utilizzare la repo perchè sul mio raspberry pi4 Leia 18.9 installato su libreelec vorrei aggiornare la distro a MATRIX 19 e non riesco diversamente.
Ho provato ad installare il pacchetto .zip 2.0.3 + matrix ma dice che la struttura non è compatibile e sia io che altri non riusciamo a farlo installare.

**Comment by AnonymousMhl** [comment]
niente da fare, ho provato ad installare la 2.0.4 +matrix :"la dipendenza xbmc.python 3.0.0 non può essere soddisfatta", mentre la 2.0.4 si è installata ma da errore non riesco a vedere nulla.

**Comment by phate89** [comment]
Ho rilasciato la repo che dovrebbe supportare anche le vecchie versioni di kodi senza problemi.. se qualcuno vuole provare e verificare mi faccia sapere

**Comment by ezu64** [comment]
Ciao sulla 18.0 restituisce l’errore dell’altro utente
