### ISSUE TITLE
Mediaset Play Errore - check the log for more information

### ISSUE THREAD

**Issue by LMussati** [phate89/Mediaset-Play-plugin.video.videomediaset#47]
Buongiorno,

Prima di tutto un bel grazie a phate89, l'ultima versione del tuo addon era veramente funzionale.

Avevo Libreelec 9.2.6 su RasPi 4 4GB e una VPN per vedere i canali italiani dall'estero.

Da una settimana però la diretta dei canali Mediaset dà l'errore del topic. Ho downgradato a Libreelec 9.2.5 e 9.2.4 con varie versioni dell'addon,  ho reinstallato più volte Libreelec e l'addon e infine aggiornato Libreelec a 9.95.1 con addon ultima versione 2.03+matrix.1 dal repo Kodi. Ho anche reinstallato più volte Widevine e provato su RasPi 3b e RasPi 4 con 2 GB, senza esito.

Ho anche provato a installare Kodi su Android, l'addon stranamente mi dà lo stesso errore.

Qualcuno ha il mio stesso problema?

Grazie a tutti e Buona Pasqua!

**Comment by Ste8826** [comment]
Stesso problema su LibreElec su RPi4/2GB.

**Comment by PuffoCyano** [comment]
Stesso problema da una settimana; ho provato sia la versione 2.0.2 che la 2.0.3; sono con Kodi v18.9. Fino a una settimana fa funzionava correttamente. In ogni caso solo le dirette e la guida TV non stanno funzionando, il resto sembra funzionare correttamente. Spero che si possa risolvere al più presto.
Grazie a tutti

**Comment by PuffoCyano** [comment]
Il problema è risolto con la seguente pull request: [https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset/pull/44](https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset/pull/44)
Quindi basta aspettare che venga integrata nella versione ufficiale :smile:

**Comment by LMussati** [comment]
Bene grazie, aspettiamo fiduciosi :-)

**Comment by marcocalm** [comment]
La pull request 44 risolve per i canali live, ma c'e' esattamente lo stesso problema per Guida TV. 
Ho ignorantemente adattato la stessa fix alla linea :303 in guida_tv_root e risolto anche per Guida TV

           if 'tuningInstruction' in prog:
-              if prog['tuningInstruction'] and not prog['mediasetstation$eventBased']:
+              if prog['tuningInstruction'] and not prog.get('mediasetstation$eventBased', False):
                    kodiutils.addListItem(prog["title"],
                                          {'mode': 'guida_tv', 'id': prog['callSign'],

**Comment by madpilot78** [comment]
@marcocalm Ho integrato il tuo suggerimento nella mia pull request.

**Comment by phate89** [comment]
https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset/releases/tag/2.0.4
Fixata qui. a breve anche su repo ufficiale

**Comment by LMussati** [comment]
Grazie, ottimo lavoro!

**Comment by PuffoCyano** [comment]
Grazie mille! Tuttavia ho trovato un nuovo errore, forse simile, durante la ricerca; nella sezione Cerca, se provo a ricercare un programma mi viene fuori lo stesso errore.

**Comment by phate89** [comment]
Ho provato a cercare e non mi usciva. Che cosa hai cercato?

**Comment by phate89** [comment]
ho provato a cercare amici in programma e con l'ultima mi ha funzionato perfettamente. mi serve un log..

**Comment by PuffoCyano** [comment]
Ok, ho reinstallato l'addon da zero e ora funziona correttamente. Grazie mille per la disponibilità e scusami per il falso allarme :smile:
