### ISSUE TITLE
Item Programmi mancante

### ISSUE THREAD

**Issue by marcocalm** [phate89/Mediaset-Play-plugin.video.videomediaset#48]
Ho visto che in un'altra issue era stato chiesto di rimettere l'elenco completo di tutte le trasmissioni, ma che questo non e' piu' presente sul sito.
Ho notato pero' che manca anche la voce Programmi TV, che e' presente sul sito, ma non piu' nella lista dell'addon.

**Comment by phate89** [comment]
Hai ragione. Pensavo fosse una cosa unica dato che nel vecchio addon era gestita in modo proprio diverso.
L'ho ripristinata e ho rilasciato una nuova versione:
https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset/releases/tag/2.0.5

**Comment by marcocalm** [comment]
Grazie, velocissimo o velocissima :)
