### ISSUE TITLE
molti video non funzionano

### ISSUE THREAD

**Issue by irontes** [phate89/Mediaset-Play-plugin.video.videomediaset#49]
Un grazie infinito per il lavoro svolto in questo fantastico addon, purtroppo credo che qualcosa sia cambiato nella struttura di mediaset poiche moltissimi video non funzionano sopratutto i piu recenti mentre online nel sito ufficiale funzionano perfettamente.
esempio: Dritto e rovescio, Svegliati amore mio, Dr. House , ecc.

**Comment by typhoon51280** [comment]
è cambiato l'attributo assetTypes da passare ai nuovi contenuti pubblicati da qualche giorno
Da qualche mese ho forkato il plugin ed iniziato a lavorarci per sperimentare con la programmazione di addon su kodi
Ho fissato il problema sulla mia versione personalizzata.
E' installabile (sia su leia che matrix) da repository [repository.typhoon51280-2.0.0.zip](https://github.com/typhoon51280/typhoon51280.github.io/raw/main/zips/repository.typhoon51280/repository.typhoon51280-2.0.0.zip) a patto di abilitare l'installazione da sorgenti sconosciute.

**Comment by phate89** [comment]
@typhoon51280 Scusa ma non puoi pubblicare qui la tua repo con una versione del mio modulo che romperebbe eventuali aggiornamenti futuri. Se io pubblicassi la 1.2.2del mio modulo non verrebbe mai installata da chi ha il tuo visto che avrebbe una versione più alta..ti chiedo di rimuoverla e se vuoi di postare il fix specifico.. altrimenti la dovrò rimuovere io..se vuoi crearepr per i cambiamenti sentiti libero di farlo
Nel frattempo sto sistemando l'addon.

**Comment by phate89** [comment]
Ho rilasciato una nuova versione con il fix:
https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset/releases/tag/2.0.6
è gia sulla mia repo e arrivera su quella ufficiale
