### ISSUE TITLE
Puntate intere non fonziona per programmi 

### ISSUE THREAD

**Issue by baggioroberto1982** [phate89/Mediaset-Play-plugin.video.videomediaset#50]
![C552C84C-453E-46FD-BF8B-A38B576E4A1E](https://user-images.githubusercontent.com/82333744/114315370-b116cf00-9acc-11eb-83d7-1f314b05abbf.jpeg)
![5C1EEB10-5B92-441B-842F-99C468E11B63](https://user-images.githubusercontent.com/82333744/114315372-b1af6580-9acc-11eb-97a3-611074692612.jpeg)

**Comment by baggioroberto1982** [comment]
Con Kodi 19 e il piu récente MediaSet Infinity.
Questo era per C’e Posta Per Te

**Comment by baggioroberto1982** [comment]
![image](https://user-images.githubusercontent.com/82333744/114315520-55007a80-9acd-11eb-81cb-1a9ae203f41b.jpg)

**Comment by baggioroberto1982** [comment]
Programma Quarto Grado, puntate intere 2021

**Comment by baggioroberto1982** [comment]
Aiuto del Canada! Gracie mille!!!

**Comment by phate89** [comment]
Scusate ho fatto un errore sistemando del codice che non centrava nulla.
Ho pubblicato una nuova release: https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset/releases/tag/2.0.7
Ho messo già l'aggiornamento sulla mia repo. Lo sto anche inviando alla repo ufficiale
