### ISSUE TITLE
le iene

### ISSUE THREAD

**Issue by SiNaPsEr0x** [phate89/Mediaset-Play-plugin.video.videomediaset#51]
salve.. abbiamo il solito problema dell'ordine dei servizi delle iene... sono tutte a cazzz 

si puo risolvere?

**Comment by phate89** [comment]
Non sono tutte a cazz. sono ordinati in data cronologica ascendente a differenza del sito (è sempre stato cosi sull'addon). Per alcuni contenuti ha piu senso (episodi di fiction per esempio) mentre per altri meno. Ho aggiunto una opzione nell'ultima versione che permette di cambiare l'ordinamento di episodi come il sito mediaset.
https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset/releases/tag/2.0.8-beta1
Si può gia trovare sulla mia repo

**Comment by SiNaPsEr0x** [comment]
Grazie mille! Ma quello delle iene dopo gli ultimi update erano davvero a cavolo come ordine

Inviato da iPhone
