### ISSUE TITLE
daydreamer il ali del sogno + guida TV not working

### ISSUE THREAD

**Issue by truresma** [phate89/Mediaset-Play-plugin.video.videomediaset#52]
Hello,

when i try to play "daydreamer il ali del sogno" under episodes it loads briefly and shows above "cache please wait" but nothing happens, this is since a couple of days

the same goes for guida tv -> canale 5

tried kodi 18.9 android tv + windows 10, 2.0.7 and 2.0.8 release

**Comment by giusy** [comment]
Same. Alle Telenovelas and Diretta on kodi 18.9/19 firetvstick with 2.0.7 and 2.0.8

**Comment by lilstar-ship-it** [comment]
same here. Tested with kodi 18.9 and 19 with 2.07 and 2.08-beta and all telenovelas + Diretta aren't working.

**Comment by phate89** [comment]
It seems to work fine for me. Can youtry again and post a log?
