### ISSUE TITLE
no champions league sectiom

### ISSUE THREAD

**Issue by lasmalein** [phate89/Mediaset-Play-plugin.video.videomediaset#59]
Since August you can watch live champions league matches with a Mediaset infinity+ account. Unfortunately there's not the champions league section and I can't watch them.

In addition I can't even watch live Mediaset Premium channels (available through a valid paid subscription)

**Comment by phate89** [comment]
RIght now login is locked so it's not possible to implement it. Even if it wasn't usually paid content have harder encryption so it's something really hard to make it work
