### ISSUE TITLE
Title in folder

### ISSUE THREAD

**Issue by mackko** [phate89/Mediaset-Play-plugin.video.videomediaset#60]
You can order title in folder from last episode to First episode. Now Is from First to last. Thanks

**Comment by phate89** [comment]
you should be able to use kodi sorting for that. OR I need an example about the wrong behavior

**Comment by mackko** [comment]
> you should be able to use kodi sorting for that. OR I need an example about the wrong behavior

Do not problems this. Problem now is that addon do not works on new Kodi 20

**Comment by phate89** [comment]
kodi with v20 now should work after the updated that will come in the next days
