### ISSUE TITLE
Has this addon been abandoned?

### ISSUE THREAD

**Issue by numbernumero** [phate89/Mediaset-Play-plugin.video.videomediaset#69]
No response in comments regarding recent issues.
Has this addon been abandoned?

**Comment by red5454** [comment]
l'autore andrebbe avvertito del problema.Lo si potrebbe contattare tramite Linkedin, ma necessita essere iscritti.Io non lo sono.Se qualcuno lo fosse potrebbe per favore raggiungerlo tramite la sua pagina:
https://it.linkedin.com/in/emanuele-guzzetti-b2b922153?original_referer=https%3A%2F%2Fwww.google.com%2F
dove in fondo si trova il link per contattarlo direttamente.
Io personalmente prometto che se riuscira' a farlo funzionare di nuovo gli faro' una donazione con Paypal.
Grazie

**Comment by marcocalm** [comment]
L'autore riceve comunque le notifiche da github. Probabilmente non ha piu' tempo/voglia di occuparsi dell'addon. Ci sta.

**Comment by phate89** [comment]
I'm trying to take back development of the addon.

**Comment by marcocalm** [comment]
Grazie!

**Comment by red5454** [comment]
grazie!!!!!
