### ISSUE TITLE
Addon non più funzionante

### ISSUE THREAD

**Issue by colonnello89** [phate89/Mediaset-Play-plugin.video.videomediaset#70]
sulla nuova versione di Kodi v20.0 (Nexus) non funge più, spero Phate89 possa risolvere quanto prima!

**Comment by MaxmaxOk** [comment]
Infatti non funziona più,purtroppo sembra che Phate89 non sia più interessato e abbia abbandonato l'addon...speriamo che un altro programmatore se ne occupi!

**Comment by phate89** [comment]
Aggiornerò a breve l'addon grazie ai contributi di madpilot78, nixxo e cristiansumma che hanno fixato questi problemi

**Comment by marcocalm** [comment]
Ottima notizia, grazie!
