### ISSUE TITLE
Errore Fork di CristianSumma compatibile con KODI 20

### ISSUE THREAD

**Issue by Dummy53** [phate89/Mediaset-Play-plugin.video.videomediaset#73]
Nel fork compatibile con KODI 20 di CristianSumma non funziona la Guida TV dove non vengono aperti i canali.
Spero venga risolto presto....
Grazie

**Comment by CristianSumma** [comment]
Grazie per la segnalazione!
Ho appena rilasciato la versione 2.0.10 che risolve questo problema.

**Comment by Dummy53** [comment]
Grazie, adesso funziona

**Comment by colonnello89** [comment]
ottimo lavoro Cristian! spero venga inserito presto anche negli add-on ufficiali

**Comment by phate89** [comment]
Aggiornerò a breve l'addon grazie ai contributi di madpilot78, nixxo e cristiansumma che hanno fixato questi problemi
